
port : 443
dateYMD : 'YYYY-MM-DD'
appBasePath: '/srv/apps/sample/src'
logBasePath: '/var/log/fw/node'

certCrt: '/etc/cert/local-fw.com/node/cert.crt'
certCsr: '/etc/cert/local-fw.com/node/cert.csr'
certKey: '/etc/cert/local-fw.com/node/cert.key'

# MySQL設定
mysqlConfig:
  host: 'db.local-fw.com'
  port: 3306
  user: 'vagrant'
  password: 'vagrant'
  database: 'sample'
  timezone: 'jst'
# Log4js設定
log4js:
  level:  'ALL'
  configure:
    appenders:
    # 開発用ログ
    - category: 'system'
      type: 'dateFile'
      filename: 'system.log'
      pattern:  '-yyyy-MM-dd'
      layout:
        type: 'pattern'
        pattern: "time:%d{ISO8601}\tlevel:%-5p\tmessage:%m"
    # エビデンス用ログ
    # パフォーマンスログ
    - category: 'performance'
      type: 'dateFile'
      filename: 'performance.log'
      pattern:  '-yyyy-MM-dd'
      layout:
        type: 'pattern'
        pattern: "time:%d{ISO8601}\t%m"
    # HTTPサーバーのアクセスログ
    - category: 'access'
      type: 'dateFile'
      filename: 'access.log'
      pattern:  '-yyyy-MM-dd'
      layout:
        type: 'messagePassThrough'
    # アプリケーションのアクセスログ(requestログ)
    - category: 'request'
      type: 'dateFile'
      filename: 'request.log'
      pattern:  '-yyyy-MM-dd'
      layout:
        type: 'messagePassThrough'
    # エラーログ
    - category: 'error'
      type: 'dateFile'
      filename: 'error.log'
      pattern:  '-yyyy-MM-dd'
      layout:
        type: 'pattern'
        pattern: "time:%d{ISO8601}\tlevel:%-5p\tmessage:%m"
accessLogFormat: "time::date\thost::remote-addr\treq:\":method :url HTTP/:http-version\"\tstatus::status\tsize:\treferrer::referrer\tua::user-agent\truntime::response-time"
