---
swagger: "2.0"
info:
  description: "`Swagger`を使用したREST APIのサンプルです\n"
  version: "1.0.0"
  title: "Sample REST API"
  termsOfService: ""
host: "node.local-fw.com"
basePath: "/v1/api"
tags:
- name: "User"
  description: "ユーザー"
- name: "Bbs"
  description: "BBS"
schemes:
- "https"
security:
- ApiSecurity:
  - "write:user"
  - "read:user"
  - "write:bbs"
  - "read:bbs"
paths:
  /users:
    get:
      tags:
      - "User"
      description: "ユーザー一覧取得"
      operationId: "listUser"
      security:
      - ApiSecurity:
        - "read:user"
      x-swagger-router-controller: "User"
    post:
      tags:
      - "User"
      description: "ユーザー追加"
      operationId: "createUser"
      security:
      - ApiSecurity:
        - "write:user"
      x-swagger-router-controller: "User"
  /users/{userId}:
    get:
      tags:
      - "User"
      description: "ユーザー取得"
      operationId: "getUser"
      security:
      - ApiSecurity:
        - "read:user"
      x-swagger-router-controller: "User"
    put:
      tags:
      - "User"
      description: "ユーザー更新"
      operationId: "updateUser"
      security:
      - ApiSecurity:
        - "write:user"
      x-swagger-router-controller: "User"
    delete:
      tags:
      - "User"
      description: "ユーザー削除"
      operationId: "deleteUser"
      security:
      - ApiSecurity:
        - "write:user"
      x-swagger-router-controller: "User"
  /bbs:
    get:
      tags:
      - "Bbs"
      description: "Bbs一覧取得"
      operationId: "listBbs"
      security:
      - ApiSecurity:
        - "read:bbs"
      x-swagger-router-controller: "Bbs"
    post:
      tags:
      - "Bbs"
      description: "BBS追加"
      operationId: "createBbs"
      security:
      - ApiSecurity:
        - "write:bbs"
      x-swagger-router-controller: "Bbs"
  /bbs/{bbsId}:
    get:
      tags:
      - "Bbs"
      description: "Bbs取得"
      operationId: "getBbs"
      security:
      - ApiSecurity:
        - "read:bbs"
      x-swagger-router-controller: "Bbs"
    put:
      tags:
      - "Bbs"
      description: "Bbs更新"
      operationId: "updateBbs"
      security:
      - ApiSecurity:
        - "write:bbs"
      x-swagger-router-controller: "Bbs"
    delete:
      tags:
      - "Bbs"
      description: "BBS削除"
      operationId: "deleteBbs"
      security:
      - ApiSecurity:
        - "write:bbs"
      x-swagger-router-controller: "Bbs"
securityDefinitions:
  ApiSecurity:
    type: "oauth2"
    authorizationUrl: "/oauth/authorize"
    tokenUrl: "/oauth/accessToken"
    flow: "accessCode"
    scopes:
      write:user: "ユーザー編集権限"
      read:user: "ユーザー参照権限"
      write:bbs: "BBS編集権限"
      read:bbs: "BBS参照権限"